language: python
python:
  - "2.7"
  - "3.8"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=3.0
install:
  - pip install Django==$DJANGO_VERSION
script: python setup.py test

# Django 2.0+ supports only Python 3.x.
matrix:
    exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=3.0
